### ISSUE TITLE
Xelatex

### ISSUE THREAD

**Issue by foxyseta** [csunibo/template#3]
Avendo già provato su github.com/csunibo/raccoglitesi a usare xelatex con successo, può avere senso tentare di usarlo anche nelle varie repo degli insegnamenti sperando non si spacchi tutto.

**Comment by foxyseta** [comment]
Solved in 4df4286

**Comment by lucat1** [comment]
Lo script `md2pdf` che usa pandoc non è stato modificato e quello continuerà ad usare pdflatex

**Comment by foxyseta** [comment]
Grazie.

**Comment by foxyseta** [comment]
Solved by [3b4d19f](https://github.com/csunibo/template/commit/3b4d19fac55342097b66bb2c23b585db1364ec11)
